---
apiVersion: "v1"
kind: "Service"
metadata:
  annotations: {}
  name: "tomcat-basic"
  labels:
    nirmata.io/service.name: "tomcat-basic"
    nirmata.io/component: "tomcat-basic"
spec:
  externalIPs: []
  loadBalancerSourceRanges: []
  type: "NodePort"
  selector:
    nirmata.io/component: "tomcat-basic"
  ports:
  - name: "http"
    nodePort: 30080
    port: 8080
    protocol: "TCP"
